
CUDA availability: True
  0%|                                                                                                                                                                                                                         | 0/496 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 129, in <module>
    main()
  File "main.py", line 125, in main
    model_trained = train(dataset, config,  device)
  File "main.py", line 78, in train
    arr_b, arr_c, arr_delta_time, event_data, non_event_data, estimate_length, choice_data_dict = batch.to(device)
AttributeError: 'list' object has no attribute 'to'