
CUDA availability: True
  0%|                                                                                                                                                                                                                         | 0/496 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 129, in <module>
    main()
  File "main.py", line 125, in main
    model_trained = train(dataset, config,  device)
  File "main.py", line 82, in train
    loss, pos_timing_loss, neg_timing_loss, choice_l = model(arr_b.float(), arr_c.float(), arr_delta_time.float(), event_data, non_event_data, estimate_length, choice_data_dict)
ValueError: not enough values to unpack (expected 4, got 3)